---
klp_mcp_server:
    # MCP Server Activation
    # Enable or disable the MCP server functionality. When disabled, no routes
    # will be registered and the server will not respond to any requests.
    enabled: true

    # Server Information
    # Configuration for the MCPServer instance. These values are used when
    # registering the MCPServer as a singleton in the service container.
    server:
        name: 'My MCP Server'
        version: '0.1.0'

    # MCP Server
    # Specify the MCP path.
    # GET  /{default_path}/sse
    # POST /{default_path}/messages (requires `sessionId` from `/sse`)
    default_path: 'mcp'

    # Ping mechanism to ensure the clients are still connected
    # This feature is optional but still useful. Disable it only if your
    # clients are not compliant and get periodically disconnected
    ############################################################################
    # WARNING:                                                                 #
    # if you need to disable this feature, make sure the connection_aborted()  #
    # behavior is not compromised by your webserver or php configuration,      #
    # otherwise your application will quickly get down with a lot of zombie    #
    # processes running.                                                       #
    # see https://www.php.net/manual/fr/function.connection-aborted.php        #
    # Create a script to test that your server configuration is ready before   #
    # sending to production                                                    #
    ############################################################################
    ping:
        enable: true
        interval: 30

    # Server-Sent Events Providers
    # The type of server providers to use. Currently, only 'streamable_http' and
    # 'sse' are supported.
    server_providers: [ 'streamable_http', 'sse' ]

    # SSE Adapters Configuration
    # Configuration for the different SSE adapters available in the MCP server.
    # Each adapter has its own configuration options.
    # Adapters function as a pub/sub message broker between clients and the
    # server. When a client sends a message to the server endpoint, the server
    # processes it and publishes a response through the adapter. SSE connections
    # subscribe to these messages and deliver them to the client in real-time.
    # The Redis adapter uses Redis lists as message queues, with each client
    # having its own queue identified by a unique client ID. This enables
    # efficient and scalable real-time communication in distributed environments
    # If a Redis server is not an option, the 'cache' adapter can be utilized
    # as an alternative
    sse_adapter: 'redis'        # Or 'cache'
    adapters:
        cache:
            prefix: 'mcp_sse_'  # Prefix for cache item keys
            ttl: 100            # Message TTL in seconds
        redis:
            prefix: 'mcp_sse_'  # Prefix for Redis keys
            host: 'localhost'   # Change it as needed
            ttl: 100            # Message TTL in seconds

    # Tools List
    # https://modelcontextprotocol.io/docs/concepts/tools
    # List of tools supported by the MCP server. These values are used when
    # generating the tool list for the client.
    # Register your tools here
    tools:
        - KLP\KlpMcpServer\Services\ToolService\Examples\CodeAnalyzerTool
        - KLP\KlpMcpServer\Services\ToolService\Examples\HelloWorldTool
        - KLP\KlpMcpServer\Services\ToolService\Examples\ProfileGeneratorTool
        - KLP\KlpMcpServer\Services\ToolService\Examples\StreamingDataTool
        - KLP\KlpMcpServer\Services\ToolService\Examples\VersionCheckTool

    # Prompts List
    # https://modelcontextprotocol.io/docs/concepts/prompts
    # List of prompts supported by the MCP server. These values are used when
    # generating the prompt list for the client.
    # Register your prompts here
    prompts:
      - KLP\KlpMcpServer\Services\PromptService\Examples\HelloWorldPrompt
      - KLP\KlpMcpServer\Services\PromptService\Examples\CodeReviewPrompt

    # Resources List
    # https://modelcontextprotocol.io/docs/concepts/resources
    resources:
        - KLP\KlpMcpServer\Services\ResourceService\Examples\HelloWorldResource
        - KLP\KlpMcpServer\Services\ResourceService\Examples\ProjectSummaryResource

    resources_templates:
        - KLP\KlpMcpServer\Services\ResourceService\Examples\McpDocumentationResource
        - KLP\KlpMcpServer\Services\ResourceService\Examples\CodeDocumentationResource
---
